### ISSUE TITLE
Issue with drillspeed for Laserdrills

### ISSUE THREAD

**Issue by Absolute359** [Anuken/Mindustry#2131]
**Platform**: *Windows 7*

**Build**: *steam build 104.10*

**Issue**: *A water boosted laserdrill on sand displays 4.94/s but it can't supply 8 oil extractors wich only need 4.8 sand/s in total. There is no overflowing sand and the oil lake on the last extractor is smaller compared to the others. For smooth designs it would be nice to get the actuall 4.94/s out of that drill*
![image](https://user-images.githubusercontent.com/66265700/83427216-ac0add00-a430-11ea-9ea5-026092d03b3e.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Katsute** [comment]
**The drill speed is not incorrect**, it does produce 4.94 sand/s. 
The final oil extractor below in both setups operate at the max speed of 15 oil/s. Occasionally the last oil extractor (left) will be slightly under due to the conveyor speed, but this is fixed using substituting it with an inverted sorter for instantaneous transport.

> the oil lake on the last extractor is smaller compared to the others

Despite how the oil appears, the oil extractor is operating at maximum speed when you hover over it, the smaller oil pool is just a visual glitch.

![20200601121110_1](https://user-images.githubusercontent.com/58778985/83428827-1b68d880-a401-11ea-8dbd-4ca4c45dae00.jpg)

**Comment by Absolute359** [comment]
Even if its only a visually glitch i would have excess sand if its really 4.94 sand/s
I tested it with different ways of transportation and allways got the same results
And other Players tested it as well
The following is as instant as it could get and still missing sand in all extractors for some ticks
![image](https://user-images.githubusercontent.com/66265700/83430470-05c1d600-a436-11ea-9dae-c968c6a14ea4.png)
