### ISSUE TITLE
Too many Puddle object

### ISSUE THREAD

**Issue by way-zer** [Anuken/Mindustry#5702]
**Platform**: *Android/iOS/Mac/Windows/Linux* Linux

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 129.2

**Issue**: *Explain your issue in detail.* OOM with 129.2 with heap max 256MB, working well with 129.1
See heap dump. More than 182MB Puddle.
![image](https://user-images.githubusercontent.com/15688938/128465216-3f365939-b649-418a-a589-d073ef8b14a9.png)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by way-zer** [comment]
heap.zip is too big(50MB), I can't upload in github

**Comment by Quezler** [comment]
~~upload it in the mindustry #bots channel on discord and just paste the link to the file here?~~

**Comment by way-zer** [comment]
> ~upload it in the mindustry #bots channel on discord and just paste the link to the file here?~

https://cdn.discordapp.com/attachments/414179246693679124/873092153633538058/heap.zip

**Comment by Anuken** [comment]
**SAVES. ARE. MANDATORY.** I'm tired of repeating this. You have not even provided a description of the map upon which this occurred, or filled in the "steps to reproduce" field. The heap dump is not useful, as my version of VisualVM doesn't even display the reference roots and *I have no way to recreate the situation*.

"Spawn a lot of puddles" clearly is not working here, because even in situation like the one shown below, my memory usage remains normal.

![image](https://user-images.githubusercontent.com/10100000/128514089-fd661b74-c4c9-47fc-a884-af98f0bdf82f.png)

**Comment by way-zer** [comment]
The heap is dump when the server crash, so i can't get the save. According to the log, this happen when gameover change map. I wiil wait it crash next time, try to get a save

**Comment by Anuken** [comment]
Enable autosave on the server, and send the latest save before the crash. I've tried running similar setups on servers and spamming slag/water puddles through various means, but that doesn't lead to any issues.

**Comment by begginerr** [comment]
i feel bad, the save is too big and the cat cant use it, but i think you should at least say how to reproduce it, at least try to find a reason why it hapenned

**Comment by begginerr** [comment]
also i have an idea for the thicc save, try to separate it into save parts that are small enough to fit in github, then the cat may be able to piece it back together and fix the bug

**Comment by Anuken** [comment]
There *is* no save, only a heap dump.

**Comment by begginerr** [comment]
oh ok

**Comment by way-zer** [comment]
I get a save before crash 7 minutes, but can't find any problem.
The server [log](https://paste.ubuntu.com/p/rVcWXXbKnx/) from save to crash.

[105.zip](https://github.com/Anuken/Mindustry/files/6954982/105.zip) (the 105 means saving on 15:50)

**Comment by Anuken** [comment]
Couldn't reproduce an issue with that map. I let it play out & game over, but even at the peak only about ~30 puddle objects were ever alive. No abnormal memory usage.

**Comment by way-zer** [comment]
> Couldn't reproduce an issue with that map. I let it play out & game over, but even at the peak only about ~30 puddle objects were ever alive. No abnormal memory usage.

I see the stack that Puddle is going to create, may solve from the stack

**Comment by Anuken** [comment]
Broken image?

**Comment by way-zer** [comment]
> Broken image?

Fixed

**Comment by Anuken** [comment]
That's actually on top of a core:

![image](https://user-images.githubusercontent.com/10100000/128722376-285ff202-eac4-418d-901f-af62300b8185.png)

**Comment by way-zer** [comment]
> That's actually on top of a core:
> 
> ![image](https://user-images.githubusercontent.com/10100000/128722376-285ff202-eac4-418d-901f-af62300b8185.png)

Oh, I forget *8, so?

**Comment by Anuken** [comment]
I don't see anything near the core that could create a puddle...

**Comment by way-zer** [comment]
Not almost, it can say all.
![image](https://user-images.githubusercontent.com/15688938/128723269-cdfd444c-7b66-47ec-ad9f-e092732ab232.png)
Is there a way to create puddle at the same position?

**Comment by Anuken** [comment]
No, that should not be possible. Only one line creates puddles, and that checks for puddle presence at a position before doing so.

**Comment by way-zer** [comment]
> No, that should not be possible. Only one line creates puddles, and that checks for puddle presence at a position before doing so.

I am trying to find more related state in the dump

**Comment by Anuken** [comment]
Is `Puddles.map` available? That maps positions to puddles.

**Comment by way-zer** [comment]
> Is `Puddles.map` available? That maps positions to puddles.

![image](https://user-images.githubusercontent.com/15688938/128725462-66f00e75-ba8d-4b36-9673-cdb1dc97734e.png)
I get it, but handle to get the entity

**Comment by way-zer** [comment]
Find the two Tile in Puddles.deposit that Tile.build is null

**Comment by Anuken** [comment]
Generation was a bad mechanic that was removed for good reason; infinite puddles in one location is a problem that should be fixed regardless.

**Comment by way-zer** [comment]
The heap dump with the save.
https://cowtransfer.com/s/5decbf381cc646
If can't download from this, call me.

**Comment by way-zer** [comment]
Happen again with 130

**Comment by Anuken** [comment]
Too many puddles in the free queue; may or may not be fixed after latest commit.

**Comment by way-zer** [comment]
Still happen in v131. More than 2000k Puddle in free queue. Almost in the same position. But I find the tile has two different value.

**Comment by way-zer** [comment]
I am using custom map-changing code. Is it wrong?
![image](https://user-images.githubusercontent.com/15688938/135805048-4feef35a-a7f4-4871-94a8-41dd9890da99.png)
While callBack is 
```kotlin
Vars.world.loadMap(info.map)
Vars.state.rules = rules
Vars.logic.play()
```

**Comment by way-zer** [comment]
![image](https://user-images.githubusercontent.com/15688938/135809162-9dd29bb3-2313-4f4c-b5ab-a4485f4a7dcc.png)
This may be the reason, the deposited will LARGE than the amount.
Then this removed, update puddle in the other tile, then deposite to this tile. Do in LOOP.
